baseURL = 'https://1himan.github.io/'
locale = 'en-us'
title = 'Himan'
theme='shibui'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
